### PR TITLE
Correct the ordering of DAILY and COMPLETE for PERIOD_PLUS

### LINKED ISSUE #143: Possible wrong direction on condition in QUERY_HISTORY_COMPLETE_AND_DAILY
line 10 has `IFF(index = PEROID_PLUS...` it is possible that this condition has been reveresed and is causing dups in #31

### PR DESCRIPTION
**Pull request by joshelser**
Re-application of #206 with extra logic to "fix" the old data through the user-facing views.

For QH and WEH tasks, we do the following:
* Record the END_TIME/SESSION_END for the next task run in `internal.config` (all rows materialized _after_ this time are correct and we don't want to invert the RECORD_TYPE on these)
* Update the views (daily, complete) to:
* * exclude any rows which span more than one day in the existing `select` (are subject to this bug)
* * union a new `select` which includes the rows that span more than one day, inverting `RECORD_TYPE`

Closes #143

### CODE REVIEW

**Comment by joshelser** [comment]
I talked about this PR with @rymurr this morning among other things.

We both felt like this current PR, while effective at "fixing" the materialized data, is not a sustainable pattern long-term. We are lucky with this change that we _can_ identify and fix the data -- Ryan's fix in #197 was not so lucky.

For fixes to materialized data that require a full re-materialization, #103 (assigned to me for this sprint) will inform users of the benefit of clicking the "reset" button, and enumerate the positives of doing so.

The outstanding question is how do we address this PR?
* Ryan believed that adding custom logic to fix the old data was not worth the debt. This would not fix materialized data (I'd remove that part of this change and rewind back to an earlier change that just fixes newly materialized data).
* Alternatively, we could treat this like a schema migration and add a procedure to re-write the offending query_id's in the materialization. This would still be one-off.

I'll give @jacques-n some time to chime in, but I'm currently leaning towards Ryan's suggestion of deferring this to #103

**Comment by jacques-n** [comment]
Isn't [this change](https://github.com/jacques-n/OpsCenter/commit/7851f64bcfa6abdae0f577dfc23b5fe3f8e5796b)

A much simpler way to fix this that also avoids a lot of debt or is there something I'm missing?

**Comment by joshelser** [comment]
> a simpler way to fix this that also avoids a lot of debt or is there something I'm missing?

Yeah, that is true. I had been trying to avoid swapping `record_type` for single-day-spanning queries and got tunnel-vision around that. Let me try out your suggestion. I think it will work and be a little more concise (at the low cost of different 'enum' values for RECORD_TYPE).

Thanks!

**Comment by joshelser** [comment]
Jacques' suggestion came out much cleaner. The only issues was having to alter the `RECORD_TYPE` column on the materialized tables from `VARCHAR(8)` to `VARCHAR`. Without this, the new values for `RECORD_TYPE` were rejected because they were longer than 8 chars.

**Review by rymurr — APPROVED** [review]
Much cleaner! Love it!

**Pull request merged**
