### PR TITLE
Minor bugfix from linking native app

### PR DESCRIPTION
**Pull request by joshelser**
1. Create the UPGRADE_CHECK task outside of FINALIZE_SETUP
2. s/internal.setup_version/internal.get_version/

### CODE REVIEW

**Comment by joshelser** [comment]
Ah, drat. I had convinced myself we could make serverless tasks outside of finalize setup. That's why you put it in there. Can come up with something else.

**Comment by joshelser** [comment]
a third one:
``` 
000904 (42000): Uncaught exception of type 'STATEMENT_ERROR' on line 13 at position 4 : SQL compilation error: error line 1 at position 39
invalid identifier 'WEB_URL'
```

maybe on the `internal.set_config(..)` calls

**Comment by joshelser** [comment]
Moved it to draft since I don't have the task creation working locally.

**Comment by rymurr** [comment]
I think the finalize task will have to be created separately by the service account

**Comment by joshelser** [comment]
> I think the finalize task will have to be created separately by the service account

Thanks. Yeah, that's what I started doing and then ran into the last bug. Will get that sorted and move this out of draft.

**Pull request closed without merging**
