### PR TITLE
Move admin.update_settings to SQL

### PR DESCRIPTION
**Pull request by joshelser**
I know you said this morning that you didn't want to go down this route, but I'm worried about the variability in latency impacting other things.

### CODE REVIEW

**Review by rymurr — COMMENTED** [review]
So we have lost validation on these settings?

**Comment by rymurr** [comment]
ive added the validations back in

**Comment by rymurr** [comment]
going to merge as josh is at an appointment this morning

**Comment by joshelser** [comment]
> So we have lost validation on these settings?

Yeah, I thought the likelihood of someone actually setting these by hand was low. I mostly thought that because i hadn't thought of just calling CONVERT_TIMEZONE like you did to validate the provided TZ. Nice trick.

**Pull request merged**
