### PR TITLE
Re-add ui elements

### PR DESCRIPTION
**Pull request by rymurr**

### CODE REVIEW

**Review by joshelser — DISMISSED** [review]

**Comment by rymurr** [comment]
@vqmarkman I've added the cypress checks back in but they don't run till I merge. Any thoguhts on how to test?

**Comment by rymurr** [comment]
I am going to merge this now so we can see how cypress tests look

**Comment by vqmarkman** [comment]
- deploy NativeApp V2 locally  as an app
- git-repo/OpsCenter/cypress/README - instructions on how to run cypress tests locally

**Pull request merged**
